"""HTML forensic report generator."""

import datetime
import json
import os


_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Forensic Report — {case_number}</title>
<style>
  body {{font-family:Arial,Helvetica,sans-serif;background:#1a1a2e;color:#e0e0e0;margin:0;padding:0}}
  .header {{background:#16213e;padding:30px 40px;border-bottom:3px solid #0f3460}}
  .header h1 {{margin:0;color:#4ecca3;font-size:28px;letter-spacing:2px}}
  .header .meta {{margin-top:10px;color:#aaa;font-size:14px}}
  .section {{margin:30px 40px}}
  .section h2 {{color:#4ecca3;border-bottom:1px solid #0f3460;padding-bottom:8px;font-size:18px}}
  table {{width:100%;border-collapse:collapse;font-size:13px;margin-bottom:20px}}
  th {{background:#0f3460;color:#4ecca3;padding:8px 12px;text-align:left}}
  td {{padding:7px 12px;border-bottom:1px solid #2a2a4a}}
  tr:hover td {{background:#1e1e3a}}
  .badge {{display:inline-block;padding:2px 8px;border-radius:12px;font-size:11px;font-weight:bold}}
  .badge-image    {{background:#1565c0;color:#fff}}
  .badge-document {{background:#2e7d32;color:#fff}}
  .badge-executable {{background:#b71c1c;color:#fff}}
  .badge-forensic {{background:#6a1b9a;color:#fff}}
  .badge-unknown  {{background:#424242;color:#fff}}
  .deleted {{color:#ef5350;font-style:italic}}
  .bookmark-note {{color:#aaa;font-size:11px;font-style:italic}}
  .ioc-email   {{color:#4a9eff}} .ioc-ip    {{color:#ff7043}}
  .ioc-url     {{color:#66bb6a}} .ioc-ssn   {{color:#ef5350}}
  .ioc-cc      {{color:#ef5350}} .ioc-btc   {{color:#ffa726}}
  .ioc-path    {{color:#ffca28}} .ioc-reg   {{color:#ff7043}}
  .footer {{text-align:center;padding:20px;color:#555;font-size:12px;border-top:1px solid #2a2a4a}}
  .summary-grid {{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:15px;margin:15px 0}}
  .stat-box {{background:#16213e;border:1px solid #0f3460;border-radius:8px;padding:15px;text-align:center}}
  .stat-box .num {{font-size:32px;font-weight:bold;color:#4ecca3}}
  .stat-box .lbl {{font-size:12px;color:#aaa;margin-top:4px}}
</style>
</head>
<body>

<div class="header">
  <h1>&#128270; Forensic Examination Report</h1>
  <div class="meta">
    <strong>Case Number:</strong> {case_number} &nbsp;&bull;&nbsp;
    <strong>Examiner:</strong> {examiner} &nbsp;&bull;&nbsp;
    <strong>Report Generated:</strong> {generated_at}
  </div>
  {description_line}
</div>

<div class="section">
  <h2>Case Summary</h2>
  <div class="summary-grid">
    <div class="stat-box"><div class="num">{evidence_count}</div><div class="lbl">Evidence Items</div></div>
    <div class="stat-box"><div class="num">{artifact_count}</div><div class="lbl">Files Analyzed</div></div>
    <div class="stat-box"><div class="num">{bookmark_count}</div><div class="lbl">Bookmarks</div></div>
    <div class="stat-box"><div class="num">{ioc_total}</div><div class="lbl">IOCs Detected</div></div>
  </div>
</div>

{evidence_section}

{artifacts_section}

{bookmarks_section}

{ioc_section}

<div class="footer">
  Report generated by <strong>aiExaminer</strong> &mdash; {generated_at}
</div>
</body>
</html>"""


def generate(db_manager, case_id: int, output_path: str,
             include_artifacts: bool = True,
             include_bookmarks: bool = True,
             include_iocs: bool = True) -> None:
    """Render and write the HTML report. Raises on write error."""

    case = db_manager.get_case_by_id(case_id)
    if case is None:
        raise ValueError(f'Case {case_id} not found in database')

    evidence_list = db_manager.get_evidence_for_case(case_id)
    artifacts     = db_manager.get_artifacts_for_case(case_id) if include_artifacts else []

    all_bookmarks: list = []
    for ev in evidence_list:
        all_bookmarks.extend(db_manager.get_bookmarks(ev.id))

    iocs: dict[str, list[str]] = {}
    if include_iocs:
        iocs = _aggregate_iocs(artifacts)

    ioc_total = sum(len(v) for v in iocs.values())
    desc_line = (f'<div class="meta"><strong>Description:</strong> {case.description}</div>'
                 if case.description else '')

    ctx = {
        'case_number':     case.case_number,
        'examiner':        case.examiner or '—',
        'generated_at':    datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        'description_line': desc_line,
        'evidence_count':  len(evidence_list),
        'artifact_count':  len(artifacts),
        'bookmark_count':  len(all_bookmarks),
        'ioc_total':       ioc_total,
        'evidence_section':  _render_evidence(evidence_list),
        'artifacts_section': _render_artifacts(artifacts) if include_artifacts else '',
        'bookmarks_section': _render_bookmarks(all_bookmarks) if include_bookmarks else '',
        'ioc_section':       _render_iocs(iocs) if include_iocs else '',
    }

    html = _TEMPLATE.format(**ctx)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)


# ------------------------------------------------------------------ #
#  Section renderers                                                    #
# ------------------------------------------------------------------ #

def _render_evidence(ev_list: list) -> str:
    if not ev_list:
        return ''
    rows = ''.join(
        f'<tr><td>{i+1}</td><td>{os.path.basename(e.image_path)}</td>'
        f'<td>{e.image_path}</td><td>{e.added_at}</td></tr>'
        for i, e in enumerate(ev_list)
    )
    return (
        '<div class="section"><h2>Evidence Items</h2>'
        '<table><tr><th>#</th><th>Filename</th><th>Full Path</th><th>Added</th></tr>'
        f'{rows}</table></div>'
    )


def _render_artifacts(artifacts: list) -> str:
    if not artifacts:
        return ''
    rows = []
    for a in artifacts:
        cat_badge = f'<span class="badge badge-{a.analysis_type.lower() if a.analysis_type else "unknown"}">{a.analysis_type or "—"}</span>'
        rows.append(
            f'<tr><td>{a.file_path}</td><td>{cat_badge}</td>'
            f'<td><code style="font-size:11px">{a.md5 or "—"}</code></td>'
            f'<td><code style="font-size:11px">{(a.sha256 or "—")[:16]}…</code></td>'
            f'<td>{a.analyzed_at}</td></tr>'
        )
    return (
        '<div class="section"><h2>Analyzed Files</h2>'
        '<table><tr><th>File Path</th><th>Type</th><th>MD5</th><th>SHA256 (partial)</th><th>Analyzed</th></tr>'
        + ''.join(rows) + '</table></div>'
    )


def _render_bookmarks(bookmarks: list) -> str:
    if not bookmarks:
        return ''
    rows = []
    for b in bookmarks:
        color = b.tag_color or '#FFDD00'
        dot = f'<span style="display:inline-block;width:12px;height:12px;border-radius:50%;background:{color};margin-right:6px"></span>'
        rows.append(
            f'<tr><td>{dot}{b.tag_name or "—"}</td>'
            f'<td>{b.file_path}</td>'
            f'<td class="bookmark-note">{b.notes or ""}</td>'
            f'<td>{b.created_at}</td></tr>'
        )
    return (
        '<div class="section"><h2>Bookmarks &amp; Tags</h2>'
        '<table><tr><th>Tag</th><th>File Path</th><th>Notes</th><th>Added</th></tr>'
        + ''.join(rows) + '</table></div>'
    )


def _render_iocs(iocs: dict) -> str:
    if not iocs:
        return ''
    _cls = {
        'Email': 'ioc-email', 'IPv4': 'ioc-ip', 'IPv6': 'ioc-ip',
        'URL': 'ioc-url', 'SSN': 'ioc-ssn', 'Credit Card': 'ioc-cc',
        'Bitcoin': 'ioc-btc', 'Ethereum': 'ioc-btc',
        'Windows Path': 'ioc-path', 'Registry Key': 'ioc-reg',
    }
    rows = []
    for kind, values in sorted(iocs.items(), key=lambda x: -len(x[1])):
        cls = _cls.get(kind, '')
        for val in sorted(set(values))[:50]:
            rows.append(
                f'<tr><td><b>{kind}</b></td>'
                f'<td class="{cls}"><code>{val}</code></td></tr>'
            )
    return (
        '<div class="section"><h2>IOC Summary</h2>'
        '<table><tr><th>Type</th><th>Value</th></tr>'
        + ''.join(rows) + '</table></div>'
    )


def _aggregate_iocs(artifacts: list) -> dict[str, list[str]]:
    """Pull IOC JSON from artifact.results if stored."""
    result: dict[str, list[str]] = {}
    for a in artifacts:
        if not a.results:
            continue
        try:
            data = json.loads(a.results)
            if isinstance(data, dict) and 'entities' in data:
                for ent in data['entities']:
                    kind = ent.get('kind', 'Unknown')
                    val  = ent.get('value', '')
                    result.setdefault(kind, []).append(val)
        except Exception:
            continue
    return result
